name: Test & Deploy
on: [workflow_dispatch]
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: what is the version
            run: node --version
          - name: npm start
            run: npm start
