name: Test & Deploy
on: workflow_dispatch
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
          - name: sldfj
            run: echo "sdkhfhhk"
          - name: lsdkf
            run: echo "sdkljflkjs"
          - name: Checkout
            uses: actions/checkout@v4
