name: Test & Deploy
on: workflow_dispatch
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: npm install
            run: npm install
          - name: npm start
